[tools]
bat = "latest"
chezmoi = "latest"
delta = "latest"
direnv = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
just = "latest"
lazygit = "latest"
ripgrep = "latest"
tmux = "latest"
starship = "latest"
yazi = "latest"
zoxide = "latest"
node = "22"
python = "3.10"
bun = "latest"
neovim = "latest"
go = "latest"
rust = "latest"
duckdb = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
