# Set lazygit to use the gitconfig file for the pager
git:
  pagers:
    - colorArg: always
      # pager: delta --paging=never --24-bit-color=never --syntax-theme base16 --line-numbers
      pager: delta -n --dark --paging=never
